- action:
    service: rest_command.ir_send
    data_template:
      blaster: '{{ trigger.json.blaster }}'
      command: '{{ trigger.json.command }}'
      target: '{{ trigger.json.target }}'
  trigger:
    platform: webhook
    webhook_id: !secret 'webhook_vacuum'
  initial_state: true
  alias: IFTTT Vacuum Control
  id: ifttt_vacuum_control
- action:
    service: notify.slack
    data:
      message: Update for Home Assistant is available.{{ '\n' }}{{ '\n' }}Potential
        Breaking Changes:{{ '\n' }}```{{ states("sensor.potential_breaking_changes")
        }}```
  trigger:
    entity_id: binary_sensor.updater
    platform: state
  alias: Update Available Notifications
  id: notify_updates
