- action:
    service: rest_command.ir_send
    data_template:
      command: '{{ trigger.json.command }}'
      target: '{{ trigger.json.target }}'
      blaster: '{{ trigger.json.blaster }}'
  initial_state: true
  alias: IFTTT Vacuum Control
  trigger:
    platform: webhook
    webhook_id: !secret 'webhook_vacuum'
  id: ifttt_vacuum_control
- trigger:
    entity_id: updater.updater
    platform: state
  alias: Update Available Notifications
  action:
    data:
      message: Update for Home Assistant is available.{{ '\n' }}{{ '\n' }}Potential
        Breaking Changes:{{ '\n' }}```{{ states("sensor.potential_breaking_changes")
        }}```
    service: notify.slack
  id: notify_updates
