- alias: IFTTT Vacuum Control
  id: ifttt_vacuum_control
  trigger:
    webhook_id: !secret 'webhook_vacuum'
    platform: webhook
  initial_state: true
  action:
    data_template:
      blaster: '{{ trigger.json.blaster }}'
      target: '{{ trigger.json.target }}'
      command: '{{ trigger.json.command }}'
    service: rest_command.ir_send
- alias: Update Available Notifications
  id: notify_updates
  trigger:
    entity_id: updater.updater
    platform: state
  action:
    data:
      message: Update for Home Assistant is available.
    service: notify.slack
