id: ifttt_vacuum_control
alias: IFTTT Vacuum Control
initial_state: true
trigger:
  platform: webhook
  webhook_id: '!secret webhook_id_ifttt'
action:
  service: rest_command.ir_send
  data_template:
    blaster: '{{ trigger.json.blaster }}'
    target: '{{ trigger.json.target }}'
    command: '{{ trigger.json.command }}'
