- action:
    service: rest_command.ir_send
    data_template:
      target: '{{ trigger.json.target }}'
      blaster: '{{ trigger.json.blaster }}'
      command: '{{ trigger.json.command }}'
  initial_state: true
  trigger:
    platform: webhook
    webhook_id: !secret 'webhook_vacuum'
  id: ifttt_vacuum_control
  alias: IFTTT Vacuum Control
- action:
    service: notify.slack
    data:
      message: Update for Home Assistant is available.
  trigger:
    platform: state
    entity_id: updater.updater
  id: notify_updates
  alias: Update Available Notifications
