- platform: mqtt
  unique_id: living_room_sensor_motion
  device_class: motion
  name: Living Room Motion
  payload_on: active
  payload_off: inactive
  state_topic: smartthings/Living Room Sensor/motion
- platform: mqtt
  unique_id: master_bedroom_sensor_motion
  device_class: motion
  name: Bedroom Motion
  payload_on: active
  payload_off: inactive
  state_topic: smartthings/Master Bedroom Sensor/motion
- platform: mqtt
  unique_id: front_door_lock_smoke
  device_class: smoke
  name: Front Door Smoke
  payload_on: detected
  payload_off: clear
  state_topic: smartthings/Front Door Lock/smoke
- platform: mqtt
  unique_id: raman_home
  device_class: presence
  name: Raman Home Presence
  payload_on: present
  payload_off: not present
  state_topic: smartthings/Raman/presence
- platform: mqtt
  unique_id: sherene_home
  device_class: presence
  name: Sherene Home Presence
  payload_on: present
  payload_off: not present
  state_topic: smartthings/Sherene/presence
