mqtt:
  port: !secret 'port_mqtt'
  broker: !secret 'host_mqtt'
hacs: !include 'hacs.yaml'
sensor: !include 'sensor.yaml'
googlehome: !include 'googlehome.yaml'
updater:
  reporting: false
binary_sensor: !include 'binary_sensor.yaml'
script: !include 'scripts.yaml'
rest_command: !include 'rest_command.yaml'
zone: !include 'zones.yaml'
homeassistant:
  unit_system: imperial
  latitude: !secret 'lat_home'
  customize: !include 'customize.yaml'
  auth_providers:
  - type: homeassistant
  longitude: !secret 'long_home'
  name: Home
  time_zone: America/New_York
  elevation: !secret 'elevation_home'
group: !include 'groups.yaml'
map:
http:
  base_url: !secret 'url_base'
  ssl_key: /cert/privkey.pem
  ssl_certificate: /cert/fullchain.pem
light: !include 'light.yaml'
frontend: !include 'frontend.yaml'
breaking_changes:
sun:
config:
history:
automation: !include 'automations.yaml'
recorder:
  purge_interval: 1
  purge_keep_days: 30
media_player: !include 'media_player.yaml'
roku: !include 'roku.yaml'
tts:
- platform: google_translate
ssdp:
conversation:
person: !include 'person.yaml'
zeroconf:
discovery:
  ignore:
  - plex_mediaserver
  - roku
lock: !include 'lock.yaml'
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
lovelace:
climate: !include 'climate.yaml'
logbook:
asuswrt: !include 'asuswrt.yaml'
device_tracker: !include 'device_tracker.yaml'
weather: !include 'weather.yaml'
system_health:
notify: !include 'notify.yaml'
