device_tracker: !include 'device_tracker.yaml'
googlehome: !include 'googlehome.yaml'
system_health:
discovery:
  ignore:
  - plex_mediaserver
  - roku
tts:
- platform: google_translate
breaking_changes:
frontend: !include 'frontend.yaml'
updater:
  reporting: false
conversation:
sun:
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
roku: !include 'roku.yaml'
person: !include 'person.yaml'
http:
  base_url: !secret 'url_base'
  ssl_key: /cert/privkey.pem
  ssl_certificate: /cert/fullchain.pem
notify: !include 'notify.yaml'
zeroconf:
ssdp:
sensor: !include 'sensor.yaml'
binary_sensor: !include 'binary_sensor.yaml'
light: !include 'light.yaml'
automation: !include 'automations.yaml'
group: !include 'groups.yaml'
map:
climate: !include 'climate.yaml'
mqtt:
  port: !secret 'port_mqtt'
  broker: !secret 'host_mqtt'
hacs: !include 'hacs.yaml'
script: !include 'scripts.yaml'
lovelace:
logbook:
homeassistant:
  auth_providers:
  - type: homeassistant
  time_zone: America/New_York
  elevation: !secret 'elevation_home'
  name: Home
  unit_system: imperial
  latitude: !secret 'lat_home'
  customize: !include 'customize.yaml'
  longitude: !secret 'long_home'
media_player: !include 'media_player.yaml'
weather: !include 'weather.yaml'
zone: !include 'zones.yaml'
asuswrt: !include 'asuswrt.yaml'
lock: !include 'lock.yaml'
recorder:
  purge_interval: 1
  purge_keep_days: 30
rest_command: !include 'rest_command.yaml'
config:
history:
