rest_command: !include 'rest_command.yaml'
http:
  ssl_certificate: /cert/fullchain.pem
  ssl_key: /cert/privkey.pem
  base_url: !secret 'url_base'
lovelace:
group: !include 'groups.yaml'
updater:
  reporting: false
logbook:
roku: !include 'roku.yaml'
conversation:
sensor: !include 'sensor.yaml'
script: !include 'scripts.yaml'
breaking_changes:
light: !include 'light.yaml'
discovery:
  ignore:
  - plex_mediaserver
  - roku
person: !include 'person.yaml'
media_player: !include 'media_player.yaml'
zone: !include 'zones.yaml'
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
tts:
- platform: google_translate
sun:
climate: !include 'climate.yaml'
history:
mqtt:
  broker: !secret 'host_mqtt'
  port: !secret 'port_mqtt'
asuswrt: !include 'asuswrt.yaml'
ssdp:
map:
binary_sensor: !include 'binary_sensor.yaml'
hacs: !include 'hacs.yaml'
frontend: !include 'frontend.yaml'
notify: !include 'notify.yaml'
device_tracker: !include 'device_tracker.yaml'
recorder:
  purge_interval: 1
  purge_keep_days: 30
system_health:
zeroconf:
weather: !include 'weather.yaml'
automation: !include 'automations.yaml'
config:
homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/New_York
  longitude: !secret 'long_home'
  elevation: !secret 'elevation_home'
  customize: !include 'customize.yaml'
  auth_providers:
  - type: homeassistant
  latitude: !secret 'lat_home'
lock: !include 'lock.yaml'
