frontend:
config:
history:
logbook:
map:

homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret long_home
  elevation: !secret elevation_home
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret pass_api
  ssl_certificate: /cert/fullchain.pem
  ssl_key: /cert/privkey.pem
  base_url: !secret url_base

updater:
  reporting: false

discovery:
  ignore:
    - plex_mediaserver
    - roku

conversation:
sun:
lovelace:

weather: !include component_configs/weather.yaml
sensor: !include component_configs/sensor.yaml
media_player: !include component_configs/media_player.yaml
roku: !include component_configs/roku.yaml
lock: !include component_configs/lock.yaml
light: !include component_configs/light.yaml
climate: !include component_configs/climate.yaml
device_tracker: !include component_configs/device_tracker.yaml
rest_command: !include component_configs/rest_command.yaml
binary_sensor: !include component_configs/binary_sensor.yaml
notify: !include component_configs/notify.yaml
custom_updater: !include component_configs/custom_updater.yaml
#googlehome: !include component_configs/googlehome.yaml
asuswrt: !include component_configs/asuswrt.yaml

# Text to speech
tts:
  - platform: google

# MQTT
mqtt:
  broker: !secret host_mqtt
  port: !secret port_mqtt

# Zwave
#zwave:
#  usb_path: /dev/zwave
#  network_key: !secret zwave_network_key

influxdb:
  username: !secret user_influx
  password: !secret pass_influx

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
