alexa: !include 'alexa.yaml'
automation: !include 'automations.yaml'
automation split: !include_dir_list 'automations'
config:
conversation:
counter:
cover: !include 'cover.yaml'
default_config:
device_tracker: !include 'device_tracker.yaml'
ffmpeg:
folder_watcher: !include 'folder_watcher.yaml'
fontawesome:
frontend: !include 'frontend.yaml'
google_assistant: !include 'google_assistant.yaml'
history:
homeassistant: !include 'homeassistant.yaml'
homekit: !include 'homekit.yaml'
http: !include 'http.yaml'
influxdb: !include 'influxdb.yaml'
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
ios:
logbook:
logger: !include 'logger.yaml'
lovelace:
map:
mobile_app:
mqtt: !include 'mqtt.yaml'
notify: !include 'notify.yaml'
plant: !include 'plant.yaml'
proxmoxve: !include 'proxmoxve.yaml'
pyscript: !include 'pyscript.yaml'
python_script:
recorder: !include 'recorder.yaml'
rest_command: !include 'rest_command.yaml'
scene: !include 'scenes.yaml'
script: !include 'scripts.yaml'
script split: !include_dir_named 'scripts'
sensor: !include 'sensor.yaml'
spotcast: !include 'spotcast.yaml'
ssdp:
sun:
switch: !include 'switch.yaml'
system_health:
system_log:
timer:
tts: !include 'tts.yaml'
wake_on_lan:
waste_collection_schedule: !include 'waste_collection_schedule.yaml'
zeroconf:
zone: !include 'zones.yaml'
zoom: !include 'zoom.yaml'
