frontend:
config:
history:
logbook:
map:

homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret long_home
  elevation: !secret elevation_home
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret pass_api
  ssl_certificate: /cert/fullchain.pem
  ssl_key: /cert/privkey.pem
  base_url: !secret url_base

updater:
  reporting: false

discovery:
  ignore:
    - plex_mediaserver
    - roku

conversation:

sun:

weather:
  - platform: darksky
    api_key: !secret api_darksky
    update_interval:
      minutes: 15

custom_updater:
  mode: storage
  track:
    - cards
    - components
    - python_scripts
  show_installable: true
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json

lovelace:
#  mode: yaml

sensor: !include components/sensors.yaml
media_player: !include components/media_players.yaml
roku: !include components/rokus.yaml
lock: !include components/locks.yaml
light: !include components/lights.yaml
climate: !include components/climates.yaml
device_tracker: !include components/device_trackers.yaml
rest_command: !include components/rest_commands.yaml
binary_sensor: !include components/binary_sensors.yaml

asuswrt:
  host: !secret ip_router
  username: !secret user_router
  password: !secret pass_router

# Text to speech
tts:
  - platform: google

# MQTT
mqtt:
  broker: !secret host_mqtt
  port: !secret port_mqtt

# Zwave
#zwave:
#  usb_path: /dev/zwave
#  network_key: !secret zwave_network_key

influxdb:
  username: !secret user_influx
  password: !secret pass_influx

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
