config:
history:
logbook:
map:
mobile_app:
system_log:
system_health:
recorder: !include 'recorder.yaml'
influxdb: !include 'influxdb.yaml'
homeassistant:
  name: Home
  latitude: !secret 'lat_home'
  longitude: !secret 'long_home'
  elevation: !secret 'elevation_home'
  unit_system: imperial
  time_zone: America/New_York
  external_url: !secret 'url_base'
  customize: !include 'customize.yaml'
  auth_providers:
  - type: homeassistant
http: !include 'http.yaml'
discovery: !include 'discovery.yaml'
ssdp:
zeroconf:
cast:
conversation:
sun:
lovelace:
frontend: !include 'frontend.yaml'
sensor: !include 'sensor.yaml'
media_player: !include 'media_player.yaml'
roku: !include 'roku.yaml'
vizio: !include 'vizio.yaml'
pi_hole: !include 'pihole.yaml'
device_tracker: !include 'device_tracker.yaml'
rest_command: !include 'rest_command.yaml'
notify: !include 'notify.yaml'
hacs: !include 'hacs.yaml'
breaking_changes:
asuswrt: !include 'asuswrt.yaml'
nzbget: !include 'nzbget.yaml'
transmission: !include 'transmission.yaml'
tts: !include 'tts.yaml'
mqtt: !include 'mqtt.yaml'
synology_dsm: !include 'synology_dsm.yaml'
spotify: !include 'spotify.yaml'
automation: !include 'automations.yaml'
automation split: !include_dir_list 'automations'
scene: !include 'scenes.yaml'
script: !include_dir_named 'scripts'
zone: !include 'zones.yaml'
fontawesome: !include 'fontawesome.yaml'
python_script:
zoom: !include 'zoom.yaml'
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
counter:
timer:
google_assistant: !include 'google_assistant.yaml'
pyscript: !include 'pyscript.yaml'
spotcast: !include 'spotcast.yaml'
xbox: !include 'xbox.yaml'
