media_player: !include 'media_player.yaml'
roku: !include 'roku.yaml'
zeroconf:
rest_command: !include 'rest_command.yaml'
logbook:
http:
  ssl_certificate: /cert/fullchain.pem
  ssl_key: /cert/privkey.pem
  base_url: !secret 'url_base'
history:
person: !include 'person.yaml'
sensor: !include 'sensor.yaml'
climate: !include 'climate.yaml'
frontend: !include 'frontend.yaml'
googlehome: !include 'googlehome.yaml'
zone: !include 'zones.yaml'
homeassistant:
  time_zone: America/New_York
  latitude: !secret 'lat_home'
  customize: !include 'customize.yaml'
  name: Home
  unit_system: imperial
  longitude: !secret 'long_home'
  auth_providers:
  - type: homeassistant
  elevation: !secret 'elevation_home'
group: !include 'groups.yaml'
device_tracker: !include 'device_tracker.yaml'
sun:
config:
lock: !include 'lock.yaml'
breaking_changes:
weather: !include 'weather.yaml'
tts:
- platform: google_translate
mqtt:
  port: !secret 'port_mqtt'
  broker: !secret 'host_mqtt'
notify: !include 'notify.yaml'
updater:
  reporting: false
asuswrt: !include 'asuswrt.yaml'
conversation:
discovery:
  ignore:
  - plex_mediaserver
  - roku
system_health:
map:
automation: !include 'automations.yaml'
light: !include 'light.yaml'
recorder:
  purge_keep_days: 30
  purge_interval: 1
ssdp:
script: !include 'scripts.yaml'
lovelace:
binary_sensor: !include 'binary_sensor.yaml'
hacs: !include 'hacs.yaml'
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
