logbook:
roku: !include 'roku.yaml'
history:
googlehome: !include 'googlehome.yaml'
device_tracker: !include 'device_tracker.yaml'
system_health:
group: !include 'groups.yaml'
ssdp:
map:
config:
discovery:
  ignore:
  - plex_mediaserver
  - roku
automation: !include 'automations.yaml'
media_player: !include 'media_player.yaml'
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
script: !include 'scripts.yaml'
http:
  ssl_certificate: /cert/fullchain.pem
  base_url: !secret 'url_base'
  ssl_key: /cert/privkey.pem
weather: !include 'weather.yaml'
conversation:
frontend: !include 'frontend.yaml'
lovelace:
mqtt:
  broker: !secret 'host_mqtt'
  port: !secret 'port_mqtt'
hacs: !include 'hacs.yaml'
asuswrt: !include 'asuswrt.yaml'
light: !include 'light.yaml'
lock: !include 'lock.yaml'
tts:
- platform: google_translate
rest_command: !include 'rest_command.yaml'
recorder:
  purge_keep_days: 30
  purge_interval: 1
sensor: !include 'sensor.yaml'
homeassistant:
  name: Home
  latitude: !secret 'lat_home'
  auth_providers:
  - type: homeassistant
  customize: !include 'customize.yaml'
  elevation: !secret 'elevation_home'
  time_zone: America/New_York
  longitude: !secret 'long_home'
  unit_system: imperial
zeroconf:
climate: !include 'climate.yaml'
updater:
binary_sensor: !include 'binary_sensor.yaml'
zone: !include 'zones.yaml'
notify: !include 'notify.yaml'
sun:
