tts:
- platform: google_translate
lock: !include 'lock.yaml'
breaking_changes:
asuswrt: !include 'asuswrt.yaml'
light: !include 'light.yaml'
discovery:
  ignore:
  - plex_mediaserver
  - roku
hacs: !include 'hacs.yaml'
mqtt:
  port: !secret 'port_mqtt'
  broker: !secret 'host_mqtt'
lovelace:
frontend: !include 'frontend.yaml'
sun:
binary_sensor: !include 'binary_sensor.yaml'
updater:
  reporting: false
zeroconf:
homeassistant:
  auth_providers:
  - type: homeassistant
  unit_system: imperial
  time_zone: America/New_York
  longitude: !secret 'long_home'
  customize: !include 'customize.yaml'
  elevation: !secret 'elevation_home'
  latitude: !secret 'lat_home'
  name: Home
sensor: !include 'sensor.yaml'
recorder:
  purge_interval: 1
  purge_keep_days: 30
notify: !include 'notify.yaml'
zone: !include 'zones.yaml'
map:
ssdp:
climate: !include 'climate.yaml'
system_health:
person: !include 'person.yaml'
rest_command: !include 'rest_command.yaml'
device_tracker: !include 'device_tracker.yaml'
group: !include 'groups.yaml'
history:
roku: !include 'roku.yaml'
logbook:
conversation:
weather: !include 'weather.yaml'
http:
  ssl_key: /cert/privkey.pem
  base_url: !secret 'url_base'
  ssl_certificate: /cert/fullchain.pem
script: !include 'scripts.yaml'
influxdb:
  username: !secret 'user_influx'
  password: !secret 'pass_influx'
media_player: !include 'media_player.yaml'
automation: !include 'automations.yaml'
config:
