map:
frontend: !include 'frontend.yaml'
system_health:
roku: !include 'roku.yaml'
tts:
- platform: google_translate
device_tracker: !include 'device_tracker.yaml'
sun:
notify: !include 'notify.yaml'
asuswrt: !include 'asuswrt.yaml'
zeroconf:
breaking_changes:
climate: !include 'climate.yaml'
lovelace:
history:
binary_sensor: !include 'binary_sensor.yaml'
updater:
lock: !include 'lock.yaml'
googlehome: !include 'googlehome.yaml'
logbook:
automation: !include 'automations.yaml'
group: !include 'groups.yaml'
http:
  ssl_certificate: /cert/fullchain.pem
  ssl_key: /cert/privkey.pem
  base_url: !secret 'url_base'
config:
weather: !include 'weather.yaml'
mqtt:
  port: !secret 'port_mqtt'
  broker: !secret 'host_mqtt'
recorder:
  purge_interval: 1
  purge_keep_days: 30
zone: !include 'zones.yaml'
ssdp:
script: !include 'scripts.yaml'
conversation:
discovery:
  ignore:
  - plex_mediaserver
  - roku
light: !include 'light.yaml'
influxdb:
  password: !secret 'pass_influx'
  username: !secret 'user_influx'
hacs: !include 'hacs.yaml'
rest_command: !include 'rest_command.yaml'
homeassistant:
  name: Home
  longitude: !secret 'long_home'
  unit_system: imperial
  elevation: !secret 'elevation_home'
  time_zone: America/New_York
  customize: !include 'customize.yaml'
  latitude: !secret 'lat_home'
  auth_providers:
  - type: homeassistant
sensor: !include 'sensor.yaml'
media_player: !include 'media_player.yaml'
