tts:
- platform: google_translate
sun:
device_tracker: !include 'device_tracker.yaml'
homeassistant:
  customize: !include 'customize.yaml'
  elevation: !secret 'elevation_home'
  unit_system: imperial
  name: Home
  auth_providers:
  - type: homeassistant
  longitude: !secret 'long_home'
  time_zone: America/New_York
  latitude: !secret 'lat_home'
group: !include 'groups.yaml'
script: !include 'scripts.yaml'
logbook:
climate: !include 'climate.yaml'
sensor: !include 'sensor.yaml'
history:
ssdp:
recorder:
  purge_keep_days: 30
  purge_interval: 1
lock: !include 'lock.yaml'
asuswrt: !include 'asuswrt.yaml'
roku: !include 'roku.yaml'
zeroconf:
media_player: !include 'media_player.yaml'
automation: !include 'automations.yaml'
hacs: !include 'hacs.yaml'
influxdb:
  username: !secret 'user_influx'
  password: !secret 'pass_influx'
lovelace:
binary_sensor: !include 'binary_sensor.yaml'
config:
person: !include 'person.yaml'
frontend: !include 'frontend.yaml'
light: !include 'light.yaml'
map:
breaking_changes:
system_health:
conversation:
discovery:
  ignore:
  - plex_mediaserver
  - roku
http:
  base_url: !secret 'url_base'
  ssl_key: /cert/privkey.pem
  ssl_certificate: /cert/fullchain.pem
notify: !include 'notify.yaml'
updater:
  reporting: false
zone: !include 'zones.yaml'
rest_command: !include 'rest_command.yaml'
mqtt:
  broker: !secret 'host_mqtt'
  port: !secret 'port_mqtt'
weather: !include 'weather.yaml'
