- platform: asuswrt
  interval_seconds: 30
  new_device_defaults:
    track_new_devices: false
    hide_if_away: false
- platform: mqtt
  devices:
    monitor_raman: monitor/monitor/raman/device_tracker
    monitor_sherene: monitor/monitor/sherene/device_tracker
  source_type: bluetooth_le
- platform: mqtt
  devices:
    smartthings_raman: monitor/monitor/raman/device_tracker
    smartthings_sherene: monitor/monitor/sherene/device_tracker
  source_type: gps
  payload_home: present
  payload_not_home: not present
