- platform: mqtt
  unique_id: living_room_light
  brightness_command_topic: smartthings/Living Room Light/level
  brightness_scale: 100
  command_topic: smartthings/Living Room Light/switch
  name: Living Room Light
  retain: true
  payload_on: 'on'
  payload_off: 'off'
  state_topic: smartthings/Living Room Light/switch
  brightness_state_topic: smartthings/Living Room Light/level
