- platform: kodi
  host: !secret 'host_living_room_shield'
  name: Living Room Kodi
- adbkey: /config/android/adbkey
  platform: androidtv
  host: !secret 'host_living_room_shield'
  name: Living Room ShieldTV
- platform: kodi
  host: !secret 'host_bedroom_firetv'
  name: Bedroom Kodi
- adbkey: /config/android/adbkey
  platform: androidtv
  host: !secret 'host_bedroom_firetv'
  name: Bedroom FireTV
- device_class: soundbar
  platform: vizio
  host: !secret 'host_living_room_soundbar'
  suppress_warning: true
  name: Living Room Sound Bar
- entity_namespace: plex
  platform: plex
