- platform: kodi
  host: !secret 'host_living_room_shield'
  name: Living Room Kodi
- platform: androidtv
  adbkey: /config/android/adbkey
  host: !secret 'host_living_room_shield'
  name: Living Room ShieldTV
- platform: kodi
  host: !secret 'host_bedroom_firetv'
  name: Bedroom Kodi
- platform: androidtv
  adbkey: /config/android/adbkey
  host: !secret 'host_bedroom_firetv'
  name: Bedroom FireTV
- suppress_warning: true
  platform: vizio
  device_class: soundbar
  host: !secret 'host_living_room_soundbar'
  name: Living Room Sound Bar
- entity_namespace: plex
  platform: plex
