- host: !secret 'host_living_room_shield'
  name: Living Room Kodi
  platform: kodi
- host: !secret 'host_living_room_shield'
  name: Living Room ShieldTV
  platform: androidtv
  adbkey: /config/android/adbkey
- host: !secret 'host_bedroom_firetv'
  name: Bedroom Kodi
  platform: kodi
- host: !secret 'host_bedroom_firetv'
  name: Bedroom FireTV
  platform: androidtv
  adbkey: /config/android/adbkey
- host: !secret 'host_living_room_soundbar'
  device_class: soundbar
  name: Living Room Sound Bar
  platform: vizio
  suppress_warning: true
- platform: plex
  entity_namespace: plex
