- platform: nfandroidtv
  host: !secret 'host_living_room_shield'
  name: Living Room
- platform: nfandroidtv
  host: !secret 'host_bedroom_firetv'
  name: Bedroom
- api_key: !secret 'api_slack'
  icon: ':information_source:'
  platform: slack
  default_channel: !secret 'default_channel_slack'
  name: Slack
