- scan_interval:
    minutes: 15
  forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  platform: darksky
  monitored_conditions:
  - icon
  - precip_type
  - precip_intensity
  - precip_probability
  - precip_accumulation
  - temperature
  - apparent_temperature
  - wind_speed
  - wind_gust
  - wind_bearing
  - cloud_cover
  - humidity
  - visibility
  - temperature_high
  - temperature_low
  - apparent_temperature_high
  - apparent_temperature_low
  - precip_intensity_max
  api_key: !secret 'api_darksky'
- name: Plex Media Server
  host: !secret 'host_living_room_shield'
  username: !secret 'user_plex'
  password: !secret 'pass_plex'
  server: home
  token: !secret 'token_plex'
  platform: plex
- platform: kodi_recently_added
  host: !secret 'host_nas'
- platform: radarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_radarr'
- platform: sonarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_sonarr'
- name: Raman Work Commute
  region: US
  platform: waze_travel_time
  destination: !secret 'address_work_raman'
  origin: !secret 'address_home'
  realtime: true
- name: Raman Home Commute
  region: US
  platform: waze_travel_time
  destination: !secret 'address_home'
  origin: !secret 'address_work_raman'
  realtime: true
- name: Sherene Work Commute
  region: US
  platform: waze_travel_time
  destination: !secret 'address_work_sherene'
  origin: !secret 'address_home'
  realtime: true
- name: Sherene Home Commute
  region: US
  platform: waze_travel_time
  destination: !secret 'address_home'
  origin: !secret 'address_work_sherene'
  realtime: true
- name: Pi-Hole
  monitored_conditions:
  - ads_blocked_today
  - ads_percentage_today
  - dns_queries_today
  - domains_being_blocked
  - queries_cached
  - queries_forwarded
  - unique_clients
  - unique_domains
  - clients_ever_seen
  platform: pi_hole
  host: !secret 'host_pihole'
- unique_id: front_door_lock_battery
  name: Front Door Lock Battery
  state_topic: smartthings/Front Door Lock/battery
  unit_of_measurement: '%'
  platform: mqtt
  device_class: battery
- unique_id: living_room_sensor_battery
  name: Living Room Sensor Battery
  state_topic: smartthings/Living Room Sensor/battery
  unit_of_measurement: '%'
  platform: mqtt
  device_class: battery
- unique_id: master_bedroom_sensor_battery
  name: Master Bedroom Sensor Battery
  state_topic: smartthings/Master Bedroom Sensor/battery
  unit_of_measurement: '%'
  platform: mqtt
  device_class: battery
- unique_id: thermostat_humidity
  name: Thermostat Humidity
  state_topic: smartthings/Thermostat/humidity
  unit_of_measurement: '%'
  platform: mqtt
  device_class: humidity
- unique_id: living_room_sensor_humidity
  name: Living Room Humidity
  state_topic: smartthings/Living Room Sensor/humidity
  unit_of_measurement: '%'
  platform: mqtt
  device_class: humidity
- unique_id: master_bedroom_sensor_humidity
  name: Master Bedroom Humidity
  state_topic: smartthings/Master Bedroom Sensor/humidity
  unit_of_measurement: '%'
  platform: mqtt
  device_class: humidity
- unique_id: living_room_sensor_temperature
  name: Living Room Temperature
  state_topic: smartthings/Living Room Sensor/temperature
  unit_of_measurement: "\xB0F"
  platform: mqtt
  device_class: temperature
- unique_id: master_bedroom_sensor_temperature
  name: Master Bedroom Temperature
  state_topic: smartthings/Master Bedroom Sensor/temperature
  unit_of_measurement: "\xB0F"
  platform: mqtt
  device_class: temperature
- unique_id: living_room_sensor_illuminance
  name: Living Room Illuminance
  state_topic: smartthings/Living Room Sensor/illuminance
  unit_of_measurement: lm
  platform: mqtt
  device_class: illuminance
- unique_id: master_bedroom_sensor_illuminance
  name: Master Bedroom Illuminance
  state_topic: smartthings/Master Bedroom Sensor/illuminance
  unit_of_measurement: lm
  platform: mqtt
  device_class: illuminance
