- platform: xbox_live
  api_key: !secret 'api_xbox'
  xuid:
  - '!secret xuid_xbox'
- platform: sonarr
  api_key: !secret 'api_sonarr'
  host: !secret 'host_nas'
- platform: radarr
  api_key: !secret 'api_radarr'
  host: !secret 'host_nas'
  monitored_conditions:
  - upcoming
- platform: kodi_recently_added
  host: !secret 'host_nas'
- platform: radarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_radarr'
- platform: sonarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_sonarr'
- platform: personalcapital
  email: !secret 'email_raman'
  password: !secret 'pass_personalcapital_raman'
- platform: waze_travel_time
  name: Raman Work Commute
  origin: !secret 'address_home'
  destination: !secret 'address_work_raman'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Raman Home Commute
  origin: !secret 'address_work_raman'
  destination: !secret 'address_home'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Sherene Work Commute
  origin: !secret 'address_home'
  destination: !secret 'address_work_sherene'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Sherene Home Commute
  origin: !secret 'address_work_sherene'
  destination: !secret 'address_home'
  region: US
  realtime: true
- platform: mqtt
  name: Front Door Lock Battery
  unique_id: front_door_lock_battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Front Door Lock/battery
- platform: mqtt
  name: Living Room Sensor Battery
  unique_id: living_room_sensor_battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Living Room Sensor/battery
- platform: mqtt
  name: Master Bedroom Sensor Battery
  unique_id: master_bedroom_sensor_battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Master Bedroom Sensor/battery
- platform: mqtt
  name: Thermostat Humidity
  unique_id: thermostat_humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Thermostat/humidity
- platform: mqtt
  name: Living Room Humidity
  unique_id: living_room_sensor_humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Living Room Sensor/humidity
- platform: mqtt
  name: Master Bedroom Humidity
  unique_id: master_bedroom_sensor_humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Master Bedroom Sensor/humidity
- platform: mqtt
  name: Living Room Temperature
  unique_id: living_room_sensor_temperature
  unit_of_measurement: "\xB0F"
  device_class: temperature
  state_topic: smartthings/Living Room Sensor/temperature
- platform: mqtt
  name: Master Bedroom Temperature
  unique_id: master_bedroom_sensor_temperature
  unit_of_measurement: "\xB0F"
  device_class: temperature
  state_topic: smartthings/Master Bedroom Sensor/temperature
- platform: mqtt
  name: Living Room Illuminance
  unique_id: living_room_sensor_illuminance
  unit_of_measurement: lm
  device_class: illuminance
  state_topic: smartthings/Living Room Sensor/illuminance
- platform: mqtt
  name: Master Bedroom Illuminance
  unique_id: master_bedroom_sensor_illuminance
  unit_of_measurement: lm
  device_class: illuminance
  state_topic: smartthings/Master Bedroom Sensor/illuminance
- platform: mqtt
  name: Hub Mode
  unique_id: hub_mode
  state_topic: smartthings/Hub/mode
- platform: mqtt
  name: Routine Im Back Last Execution
  unique_id: routine_im_back_last_execution
  state_topic: 'smartthings/Routine: I''m Back!/lastExecution'
  device_class: timestamp
- platform: mqtt
  name: Routine Goodbye Last Execution
  unique_id: routine_goodbye_last_execution
  state_topic: 'smartthings/Routine: Goodbye!/lastExecution'
  device_class: timestamp
- platform: mqtt
  name: Routine Good Morning Last Execution
  unique_id: routine_good_morning_last_execution
  state_topic: 'smartthings/Routine: Good Morning!/lastExecution'
  device_class: timestamp
- platform: mqtt
  name: Routine Good Night Last Execution
  unique_id: routine_good_night_last_execution
  state_topic: 'smartthings/Routine: Good Night!/lastExecution'
  device_class: timestamp
- platform: mqtt
  name: Routine Last Executed
  unique_id: routine_last_executed
  state_topic: smartthings/Routine/lastRoutineExecuted
  device_class: timestamp
- platform: version
  name: local_ha_version
  source: local
- platform: version
  name: available_ha_version
  source: docker
- platform: shodan
  name: shodan
  api_key: !secret 'api_shodan'
  query: 8.3.80.33
