- platform: personalcapital
  email: !secret 'email_raman'
  password: !secret 'pass_personalcapital_raman'
- platform: shodan
  name: shodan
  api_key: !secret 'api_shodan'
  query: !secret 'query_shodan'
- platform: waste_collection_schedule
  name: Trash Collection
  add_days_to: true
- platform: gtfs_rt
  trip_update_url: https://api.wmata.com/gtfs/bus-gtfsrt-tripupdates.pb
  vehicle_position_url: https://api.wmata.com/gtfs/bus-gtfsrt-vehiclepositions.pb
  headers:
    api_key: !secret 'api_wmata'
  departures:
  - name: 16th (local) Home to Office
    routes: !secret 'wmata_route_sherene_office_16'
    stop_id: !secret 'wmata_stop_sherene_home_16'
  - name: 16th (express) Home to Office
    routes: !secret 'wmata_route_sherene_office_16_express'
    stop_id: !secret 'wmata_stop_sherene_home_16_express'
  - name: 14th Home to Office
    routes:
    - !secret 'wmata_route_sherene_office_14_1'
    - !secret 'wmata_route_sherene_office_14_2'
    stop_id: !secret 'wmata_stop_sherene_home_14'
  - name: 16th (local) Office to Home
    routes: !secret 'wmata_route_sherene_office_16'
    stop_id: !secret 'wmata_stop_sherene_office_16'
  - name: 16th (express) Office to Home
    routes: !secret 'wmata_route_sherene_office_16_express'
    stop_id: !secret 'wmata_stop_sherene_office_16_express'
  - name: 14th Office to Home
    routes:
    - !secret 'wmata_route_sherene_office_14_1'
    - !secret 'wmata_route_sherene_office_14_2'
    stop_id: !secret 'wmata_stop_sherene_office_14'
