- api_key: !secret 'api_darksky'
  platform: darksky
  forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  scan_interval:
    minutes: 15
  monitored_conditions:
  - icon
  - precip_type
  - precip_intensity
  - precip_probability
  - precip_accumulation
  - temperature
  - apparent_temperature
  - wind_speed
  - wind_gust
  - wind_bearing
  - cloud_cover
  - humidity
  - visibility
  - temperature_high
  - temperature_low
  - apparent_temperature_high
  - apparent_temperature_low
  - precip_intensity_max
- host: !secret 'host_living_room_shield'
  platform: plex
  username: !secret 'user_plex'
  name: Plex Media Server
  token: !secret 'token_plex'
  password: !secret 'pass_plex'
  server: home
- host: !secret 'host_nas'
  platform: kodi_recently_added
- api_key: !secret 'api_radarr'
  host: !secret 'host_nas'
  platform: radarr_upcoming_media
- api_key: !secret 'api_sonarr'
  host: !secret 'host_nas'
  platform: sonarr_upcoming_media
- platform: waze_travel_time
  origin: !secret 'address_home'
  realtime: true
  name: Raman Work Commute
  destination: !secret 'address_work_raman'
  region: US
- platform: waze_travel_time
  origin: !secret 'address_work_raman'
  realtime: true
  name: Raman Home Commute
  destination: !secret 'address_home'
  region: US
- platform: waze_travel_time
  origin: !secret 'address_home'
  realtime: true
  name: Sherene Work Commute
  destination: !secret 'address_work_sherene'
  region: US
- platform: waze_travel_time
  origin: !secret 'address_work_sherene'
  realtime: true
  name: Sherene Home Commute
  destination: !secret 'address_home'
  region: US
- host: !secret 'host_pihole'
  platform: pi_hole
  monitored_conditions:
  - ads_blocked_today
  - ads_percentage_today
  - dns_queries_today
  - domains_being_blocked
  - queries_cached
  - queries_forwarded
  - unique_clients
  - unique_domains
  - clients_ever_seen
  name: Pi-Hole
- unique_id: front_door_lock_battery
  platform: mqtt
  name: Front Door Lock Battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Front Door Lock/battery
- unique_id: living_room_sensor_battery
  platform: mqtt
  name: Living Room Sensor Battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Living Room Sensor/battery
- unique_id: master_bedroom_sensor_battery
  platform: mqtt
  name: Master Bedroom Sensor Battery
  unit_of_measurement: '%'
  device_class: battery
  state_topic: smartthings/Master Bedroom Sensor/battery
- unique_id: thermostat_humidity
  platform: mqtt
  name: Thermostat Humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Thermostat/humidity
- unique_id: living_room_sensor_humidity
  platform: mqtt
  name: Living Room Humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Living Room Sensor/humidity
- unique_id: master_bedroom_sensor_humidity
  platform: mqtt
  name: Master Bedroom Humidity
  unit_of_measurement: '%'
  device_class: humidity
  state_topic: smartthings/Master Bedroom Sensor/humidity
- unique_id: living_room_sensor_temperature
  platform: mqtt
  name: Living Room Temperature
  unit_of_measurement: "\xB0F"
  device_class: temperature
  state_topic: smartthings/Living Room Sensor/temperature
- unique_id: master_bedroom_sensor_temperature
  platform: mqtt
  name: Master Bedroom Temperature
  unit_of_measurement: "\xB0F"
  device_class: temperature
  state_topic: smartthings/Master Bedroom Sensor/temperature
- unique_id: living_room_sensor_illuminance
  platform: mqtt
  name: Living Room Illuminance
  unit_of_measurement: lm
  device_class: illuminance
  state_topic: smartthings/Living Room Sensor/illuminance
- unique_id: master_bedroom_sensor_illuminance
  platform: mqtt
  name: Master Bedroom Illuminance
  unit_of_measurement: lm
  device_class: illuminance
  state_topic: smartthings/Master Bedroom Sensor/illuminance
