- platform: sonarr
  api_key: !secret 'api_sonarr'
  host: !secret 'host_nas'
- platform: radarr
  api_key: !secret 'api_radarr'
  host: !secret 'host_nas'
  monitored_conditions:
  - upcoming
- platform: kodi_recently_added
  host: !secret 'host_nas'
- platform: radarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_radarr'
- platform: sonarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_sonarr'
- platform: personalcapital
  email: !secret 'email_raman'
  password: !secret 'pass_personalcapital_raman'
- platform: waze_travel_time
  name: Raman Work Commute
  origin: !secret 'address_home'
  destination: !secret 'address_work_raman'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Raman Home Commute
  origin: !secret 'address_work_raman'
  destination: !secret 'address_home'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Sherene Work Commute
  origin: !secret 'address_home'
  destination: !secret 'address_work_sherene'
  region: US
  realtime: true
- platform: waze_travel_time
  name: Sherene Home Commute
  origin: !secret 'address_work_sherene'
  destination: !secret 'address_home'
  region: US
  realtime: true
- platform: version
  name: local_ha_version
  source: local
- platform: version
  name: available_ha_version
  source: docker
- platform: shodan
  name: shodan
  api_key: !secret 'api_shodan'
  query: 8.3.80.33
