- forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  scan_interval:
    minutes: 15
  platform: darksky
  api_key: !secret 'api_darksky'
  monitored_conditions:
  - icon
  - precip_type
  - precip_intensity
  - precip_probability
  - precip_accumulation
  - temperature
  - apparent_temperature
  - wind_speed
  - wind_gust
  - wind_bearing
  - cloud_cover
  - humidity
  - visibility
  - temperature_high
  - temperature_low
  - apparent_temperature_high
  - apparent_temperature_low
  - precip_intensity_max
- server: home
  password: !secret 'pass_plex'
  name: Plex Media Server
  host: !secret 'host_living_room_shield'
  platform: plex
  username: !secret 'user_plex'
  token: !secret 'token_plex'
- platform: kodi_recently_added
  host: !secret 'host_nas'
- platform: radarr_upcoming_media
  api_key: !secret 'api_radarr'
  host: !secret 'host_nas'
- platform: sonarr_upcoming_media
  api_key: !secret 'api_sonarr'
  host: !secret 'host_nas'
- destination: !secret 'address_work_raman'
  region: US
  name: Raman Work Commute
  realtime: true
  platform: waze_travel_time
  origin: !secret 'address_home'
- destination: !secret 'address_home'
  region: US
  name: Raman Home Commute
  realtime: true
  platform: waze_travel_time
  origin: !secret 'address_work_raman'
- destination: !secret 'address_work_sherene'
  region: US
  name: Sherene Work Commute
  realtime: true
  platform: waze_travel_time
  origin: !secret 'address_home'
- destination: !secret 'address_home'
  region: US
  name: Sherene Home Commute
  realtime: true
  platform: waze_travel_time
  origin: !secret 'address_work_sherene'
- name: Pi-Hole
  monitored_conditions:
  - ads_blocked_today
  - ads_percentage_today
  - dns_queries_today
  - domains_being_blocked
  - queries_cached
  - queries_forwarded
  - unique_clients
  - unique_domains
  - clients_ever_seen
  platform: pi_hole
  host: !secret 'host_pihole'
- device_class: battery
  state_topic: smartthings/Front Door Lock/battery
  name: Front Door Lock Battery
  unique_id: front_door_lock_battery
  platform: mqtt
  unit_of_measurement: '%'
- device_class: battery
  state_topic: smartthings/Living Room Sensor/battery
  name: Living Room Sensor Battery
  unique_id: living_room_sensor_battery
  platform: mqtt
  unit_of_measurement: '%'
- device_class: battery
  state_topic: smartthings/Master Bedroom Sensor/battery
  name: Master Bedroom Sensor Battery
  unique_id: master_bedroom_sensor_battery
  platform: mqtt
  unit_of_measurement: '%'
- device_class: humidity
  state_topic: smartthings/Thermostat/humidity
  name: Thermostat Humidity
  unique_id: thermostat_humidity
  platform: mqtt
  unit_of_measurement: '%'
- device_class: humidity
  state_topic: smartthings/Living Room Sensor/humidity
  name: Living Room Humidity
  unique_id: living_room_sensor_humidity
  platform: mqtt
  unit_of_measurement: '%'
- device_class: humidity
  state_topic: smartthings/Master Bedroom Sensor/humidity
  name: Master Bedroom Humidity
  unique_id: master_bedroom_sensor_humidity
  platform: mqtt
  unit_of_measurement: '%'
- device_class: temperature
  state_topic: smartthings/Living Room Sensor/temperature
  name: Living Room Temperature
  unique_id: living_room_sensor_temperature
  platform: mqtt
  unit_of_measurement: "\xB0F"
- device_class: temperature
  state_topic: smartthings/Master Bedroom Sensor/temperature
  name: Master Bedroom Temperature
  unique_id: master_bedroom_sensor_temperature
  platform: mqtt
  unit_of_measurement: "\xB0F"
- device_class: illuminance
  state_topic: smartthings/Living Room Sensor/illuminance
  name: Living Room Illuminance
  unique_id: living_room_sensor_illuminance
  platform: mqtt
  unit_of_measurement: lm
- device_class: illuminance
  state_topic: smartthings/Master Bedroom Sensor/illuminance
  name: Master Bedroom Illuminance
  unique_id: master_bedroom_sensor_illuminance
  platform: mqtt
  unit_of_measurement: lm
