- platform: radarr
  api_key: !secret 'api_radarr'
  host: !secret 'host_nas'
  monitored_conditions:
  - upcoming
- platform: kodi_recently_added
  host: !secret 'host_nas'
- platform: radarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_radarr'
- platform: sonarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_sonarr'
- platform: personalcapital
  email: !secret 'email_raman'
  password: !secret 'pass_personalcapital_raman'
- platform: version
  name: local_ha_version
  source: local
- platform: version
  name: available_ha_version
  source: hassio
  image: odroid-n2
- platform: shodan
  name: shodan
  api_key: !secret 'api_shodan'
  query: 8.3.80.33
