- platform: radarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_radarr'
- platform: sonarr_upcoming_media
  host: !secret 'host_nas'
  api_key: !secret 'api_sonarr'
- platform: personalcapital
  email: !secret 'email_raman'
  password: !secret 'pass_personalcapital_raman'
- platform: shodan
  name: shodan
  api_key: !secret 'api_shodan'
  query: 8.3.80.33
