id: notify_raman_off_zoom
alias: 'Notify: Raman off Zoom'
trigger:
  platform: state
  entity_id: binary_sensor.zoom_raman
  from: 'on'
  to: 'off'
  for: 00:00:15
action:
- service: pyscript.set_slack_status
  data:
    token: !secret 'token_slack'
    status_text:
    status_emoji:
