id: notify_raman_off_zoom
alias: 'Notify: Raman off Zoom'
trigger:
  platform: state
  entity_id: binary_sensor.zoom_raman
  from: 'on'
  to: 'off'
  for: 00:01:00
condition:
  condition: state
  entity_id: input_boolean.zoom_dnd_raman
  state: 'on'
action:
- service: pyscript.set_slack_status
  data:
    token: !secret 'token_slack'
    status_text:
    status_emoji:
- service: input_boolean.turn_off
  entity_id: input_boolean.zoom_dnd_raman
