id: notify_raman_on_zoom
alias: 'Notify: Raman on Zoom'
trigger:
  platform: state
  entity_id: binary_sensor.zoom_raman
  from: 'off'
  to: 'on'
condition:
  condition: state
  entity_id: input_boolean.zoom_dnd_raman
  state: 'off'
action:
- service: pyscript.set_slack_status
  data:
    token: !secret 'token_slack'
    status_text: On a Call
    status_emoji: ':x:'
- service: input_boolean.turn_on
  entity_id: input_boolean.zoom_dnd_raman
