id: routine_everyone_leaves
alias: 'Routine: Everyone Leaves'
trigger:
  platform: state
  entity_id: person.raman, person.sherene
  to: not_home
  for: 00:10:00
condition:
  condition: and
  conditions:
  - condition: state
    entity_id:
    - person.sherene
    - person.raman
    state: not_home
  - condition: state
    entity_id: input_select.home_mode
    state:
    - Home
    - Night
action:
  service: input_select.select_option
  data:
    entity_id: input_select.home_mode
    option: Away
