id: routine_morning
alias: 'Routine: Morning'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion, light.living_room, light.foyer, light.kitchen
  to: 'on'
condition:
  condition: and
  conditions:
  - condition: time
    after: 06:00:01
    before: '23:59:59'
  - condition: state
    entity_id: input_select.home_mode
    state: Night
action:
  service: input_select.select_option
  data:
    entity_id: input_select.home_mode
    option: Home
