id: routine_night
alias: 'Routine: Night'
trigger:
  platform: time_pattern
  minutes: /1
  hours: '*'
condition:
  alias: Check that home mode is Home, it's between midnight and 6 AM, and there has
    been no motion in the living room for 20 minutes
  and:
  - condition: state
    entity_id: input_select.home_mode
    state: Home
  - condition: time
    after: 00:00:00
    before: 06:00:00
  - condition: state
    entity_id: binary_sensor.living_room_motion
    state: 'off'
    for: 00:20:00
action:
- alias: Set Home Mode to Night
  service: input_select.select_option
  data:
    entity_id: input_select.home_mode
    option: Night
- alias: Disable the Night Routine
  service: automation.turn_off
  data:
    entity_id: automation.routine_night
