id: routine_night
alias: 'Routine: Night'
trigger:
  platform: time_pattern
  minutes: /1
  hours: '*'
condition:
  condition: and
  conditions:
  - condition: time
    after: 00:00:00
    before: 06:00:00
  - condition: template
    value_template: '{{ is_state("binary_sensor.living_room_motion", "off") }}'
  - condition: template
    value_template: '{{ is_state("input_select.home_mode", "Home") }}'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.home_mode
    option: Night
