- platform: mqtt
  name: "Living Room Motion"
  unique_id: living_room_sensor_motion
  device_class: "motion"
  state_topic: "smartthings/Living Room Sensor/motion"
  payload_on: "active"
  payload_off: "inactive"

- platform: mqtt
  name: "Bedroom Motion"
  unique_id: master_bedroom_sensor_motion
  device_class: "motion"
  state_topic: "smartthings/Master Bedroom Sensor/motion"
  payload_on: "active"
  payload_off: "inactive"

- platform: mqtt
  name: "Front Door Smoke"
  unique_id: front_door_lock_smoke
  device_class: "smoke"
  state_topic: "smartthings/Front Door Lock/smoke"
  payload_on: "detected"
  payload_off: "clear"

- platform: mqtt
  name: "Raman's Home Presence"
  unique_id: raman_home
  device_class: "presence"
  state_topic: "smartthings/Raman/presence"
  payload_on: "present"
  payload_off: "not present"

- platform: mqtt
  name: "Sherene's Home Presence"
  unique_id: sherene_home
  device_class: "presence"
  state_topic: "smartthings/Sherene/presence"
  payload_on: "present"
  payload_off: "not present"
