- platform: kodi
  name: "Living Room Kodi"
  host: !secret ip_living_room_kodi

- platform: kodi
  name: "Bedroom Kodi"
  host: !secret ip_bedroom_firetv

- platform: firetv
  name: "Bedroom FireTV"
  host: !secret ip_bedroom_firetv
