id: home_mode_away
alias: 'Home Mode: Away'
trigger:
  platform: state
  entity_id: input_select.home_mode
  to: Away
action:
- alias: lock down the house
  service: pyscript.lock_down
- alias: Set temperature based on away mode thresholds
  service: climate.set_temperature
  target:
    entity_id: climate.thermostat
  data:
    temperature: '{% if states(''climate.thermostat'') == ''heat'' %}{{ states(''input_number.away_low'')
      }}{% else %}{{ states(''input_number.away_high'') }}{% endif %}'
