id: home_mode_away
alias: 'Home Mode: Away'
trigger:
  platform: state
  entity_id: input_select.home_mode
  to: Away
action:
- service: script.lock_down
- service: script.set_temperature
  data:
    mode: away
