id: home_mode_away
alias: 'Home Mode: Away'
trigger:
  platform: state
  entity_id: input_select.home_mode
  to: Away
action:
- alias: lock down the house
  service: pyscript.lock_down
- alias: Set temperature mode to away
  service: pyscript.set_temperature
  data:
    mode: away
