id: home_mode_home
alias: 'Home Mode: Home'
trigger:
  platform: state
  entity_id: input_select.home_mode
  to: Home
action:
- alias: Set temperature mode to home
  service: pyscript.set_temperature
  data:
    mode: home
