id: home_mode_night
alias: 'Home Mode: Night'
trigger:
  platform: state
  entity_id: input_select.home_mode
  to: Night
action:
- service: script.lock_down
- service: script.set_temperature
  data:
    mode: night
