id: ifttt_vacuum_control
alias: 'IFTTT: Vacuum Control'
initial_state: true
trigger:
  platform: webhook
  webhook_id: !secret 'webhook_vacuum'
condition: !secret 'webhook_auth_check'
action:
  alias: Send the appropriate IR command to the vacuum
  service: rest_command.ir_send
  data_template:
    target: '{{ trigger.json.target }}'
    command: '{{ trigger.json.command }}'
