id: no_hacs_updates
alias: 'Notify: HACS updates completed'
trigger:
  platform: state
  entity_id: sensor.hacs
condition: '{{ states("sensor.hacs")|int == 0 }}'
action:
- service: persistent_notification.dismiss
  data:
    notification_id: hacs_update
