id: notify_washer_off
alias: 'Notify: Washer is off'
trigger:
  platform: numeric_state
  entity_id: sensor.washer_electric_consumption_w
  below: 0.5
condition:
  condition: state
  entity_id: input_boolean.washer
  state: 'on'
action:
- service: input_boolean.turn_off
  data:
    entity_id: input_boolean.washer
- service: notify.mobile_app_ramans_iphone
  data:
    title: Washer Done!
    message: Washer done
    data:
      tag: washer-done-check-in
      action_data:
        entity_id: lock.front_door
      actions:
      - action: washer-done-check-in
        title: Check in
