id: misc_turn_off_blanket_on_ha_start
alias: 'Misc: Turn Off Blanket on HA Start'
trigger:
  platform: homeassistant
  event: start
condition:
  condition: state
  entity_id: switch.sherene_electric_blanket_plug
  state: 'on'
action:
- service: switch.turn_off
  entity_id: switch.sherene_electric_blanket_plug
